### ISSUE TITLE
Wake lock

### ISSUE THREAD

**Issue by OwnageIsMagic** [niranjan94/show-java#10]
Acquire wake lock while decompiling + add dark theme for amoled devices (almost white screen for 10 mins really hurts my phone battery)

**Comment by niranjan94** [comment]
You don't have to keep screen open. You can close the app when the
decompiler is running. The decompiler runs on a foreground service and will
not get killed when you close the app.
So, I feel a wake lock for a foreground service is unnecessary. As for the
dark theme. I'll add it :-)
