### ISSUE TITLE
Doesn't provide complete source code. 

### ISSUE THREAD

**Issue by Sidharth99** [niranjan94/show-java#100]
The source code we get after decompiling is not completely as that of source code.. I found many lines missing and changes in words too. The actual code consists 609 lines and but the app provided 596 lines. Though I found the app awesome, will be better if you provide the complete source code.

**Comment by niranjan94** [comment]
Decompilation is never a complete process. There will always be holes and parts which the decompiler isn't able to decompile. 

What you could do is, try all the three provided decompilers and use the one that gives the best output.
