### ISSUE TITLE
JaDX0.6.1 - The app you selected cannot be decompiled. Please select another app

### ISSUE THREAD

**Issue by MrNull42** [niranjan94/show-java#129]
I've been getting this message a lot lately with many different apps including previous ones that It worked on.

Can anyone provide more details? Error message isn't helpful.
Also if you can provide directions I'll try looking into it myself(android)

**Comment by ZeevM3** [comment]
is it possible to replace the JaDX with the newer version?

**Comment by niranjan94** [comment]
@MrNull42 yep. I'm actually _finally_ working on a new version. That will have updated versions of all of the decompilers along with some other nice improvements.

**Comment by AxelCC** [comment]
I got the same problem with both decompilers with app that before was decompiled

**Comment by MrNull42** [comment]
@niranjan94 what's funny bout my question?
