### ISSUE TITLE
bug with show-java

### ISSUE THREAD

**Issue by Andyfrc08** [niranjan94/show-java#13]
1) I decompiled an app, then I updated the app, and now show-java doesn't decompile it anymore

2) I tried to deinstall and _clean_ the cache, but when I reinstall it another app which I also decompiled is still there, with all its java and layouts...

**Comment by niranjan94** [comment]
1) Goto settings -> applications -> ShowJava -> Clear cache & Clear data. Now try to decompile. It will work
2) Even if you uninstall ShowJava, any app that was decompiled previously will still be available inside the ShowJava folder in the sdcard.

**Comment by Andyfrc08** [comment]
action 1) alone was not successful (I could no longer re-decompile an app
after having updated it)

but after having de-installed show-java _and_ deleted its folder, and
reinstalled show-java, then it worked again (and I could check that my
updated app was using the new java code)
Le 8 oct. 2015 16:40, "Niranjan Rajendran" <notifications@github.com> a
écrit :

**Comment by Andyfrc08** [comment]
Hello,

here is a bug

1) I installed an app A once
2) I decompiled it
3) I installed an update of A
4) I tried to decompile the new version
5) your program told and asked me "this program has already been
decompiled. What do you want to do? View decompilation? Decompile?"
6) I checked 'decompile'

then your program is stuck, with a cogwheel rotating, in "getting ready"

AC
Le 8 oct. 2015 16:40, "Niranjan Rajendran" <notifications@github.com> a
écrit :

**Comment by niranjan94** [comment]
Hi,

Goto settings -> applications -> ShowJava -> Clear cache & Clear data. Now
try to decompile. It will work.

Thanks,
Niranjan R
