### ISSUE TITLE
to see  the origan code

### ISSUE THREAD

**Issue by nira30kumar** [niranjan94/show-java#16]
Your app is gud.. no doubt.. but last two days  i am  used  your app but this will not work not  decompile any android app..  before up dating ur app is working very well nd compile.. u  provide twi types decompiler in  ur ap no one  useable

**Comment by niranjan94** [comment]
Hi ... this is a common issue faced by few ... (as referred to in issue #9) .... 
All you have to do is, goto 
Settings>Apps>Show Java>Clear Cache and Clear data

**Comment by nira30kumar** [comment]
then now ur app will work nd show tha source code
