### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by HeatherHeath5** [niranjan94/show-java#18]
James williams has hacked my phone and everything I have on line. I vany access any of my emails he has made new ones under my name and my web pages name. He has hacked every web page I have. He is also a user of this sit and github. I'm sure he has gotten into my accounts there also. His email is uhwaccu@gmail.com

**Comment by niranjan94** [comment]
Why are you putting it here ?

**Comment by AdLindsay** [comment]
@HeatherHeath5 Search Google for
 'get revenge email'
without the quotes, there's some really interesting stuff. But also remember to use a  VPN or proxy or use someone else's WiFi who doesn't live near you.

**Comment by HeatherHeath5** [comment]
I didn't even do this WOW he uploaded every email I sent and everything to random places. I apologize for this!!
