### ISSUE TITLE
decompile failed

### ISSUE THREAD

**Issue by maggu2810** [niranjan94/show-java#2]
To test the app I tried to decompile Keepass2Android 0.9.7b.
It seems that the sources couldn't be decompiled.
I am using a Nexus 5 running the Android M developer preview 3.

<pre>
Summary for /storage/emulated/0/ShowJava/sources/keepass2android.keepass2android/keepass2android.keepass2android.jar
Decompiled with CFR 0_102
Exception analysing jar org.benf.cfr.reader.util.ConfusedCFRException: Failed to load jar /storage/emulated/0/ShowJava/sources/keepass2android.keepass2android/keepass2android.keepass2android.jar
</pre>

**Comment by niranjan94** [comment]
Thanks for sharing the issue. Working on it.

**Comment by maggu2810** [comment]
Do you need some futher testing?
Why have you to reopen this issue?

**Comment by niranjan94** [comment]
A similar issue was faced by another user. He has provided me with the the decompiler message and the apk he tried to decompile. I'm currently working on it.

**Comment by niranjan94** [comment]
Hi, commit dc67cffbbcc451d4b918e32dc67c926051260dff adds an option to use JaDX as a decompiler. JaDX is able to decompile apks that cannot be decompiled by CFR.

**Comment by maggu2810** [comment]
Thank you. I will have a look at on the next release.
