### ISSUE TITLE
Restoring ad-free license after reinstallation.

### ISSUE THREAD

**Issue by ghost** [niranjan94/show-java#213]
![Screenshot_2021-09-24-13-39-22-738_com njlabs showjava](https://user-images.githubusercontent.com/37485357/134668522-48d5a66c-d998-48fd-a5d6-284e79a636cf.jpg)

**Comment by niranjan94** [comment]
Hi @mistergoliath41 . Please drop in an email to me at `me@niranjan.io` with the email address you used for your purchase. Will get this sorted at the earliest.
