### ISSUE TITLE
rate and review ipointing to nonfunctional playstore and galaxy store linksstore links 

### ISSUE THREAD

**Issue by staleysolutions** [niranjan94/show-java#238]
I was curious wherein the code this function is called to see whether I can fix it myself if anyone knows. I'll fork it myself and look in the interim...

**Comment by creativetrendsapps** [comment]
> I was curious wherein the code this function is called to see whether I can fix it myself if anyone knows. I'll fork it myself and look in the interim...

https://github.com/niranjan94/show-java/blob/development/app/src/main/res/xml/preferences.xml[It's an intent called from the preferences.xml file](https://github.com/niranjan94/show-java/blob/development/app/src/main/res/xml/preferences.xml)

**Comment by creativetrendsapps** [comment]
> I was curious wherein the code this function is called to see whether I can fix it myself if anyone knows. I'll fork it myself and look in the interim...

[It is an intent called in the preferences file](https://github.com/niranjan94/show-java/blob/development/app/src/main/res/xml/preferences.xml#L142)
