### ISSUE TITLE
Camera issues 

### ISSUE THREAD

**Issue by Fernall** [niranjan94/show-java#25]
After ported Legoice_fusion_v5 jb 4.2.2 custom rom  development by "sagarwep" on my phone, camera and wife not working but show message "unfortunately gallery has stopped" 
Please help me. 
Sorry for bad English write. 
My email : persianbaz@gmail.com
Thanks for you.

**Comment by niranjan94** [comment]
This is the issues page of the Show Java android application. Only problems about that app has to be posted here. For your issue, please contact the rom developer.
