### ISSUE TITLE
Decompiling not working on my Samsung GT-N7100

### ISSUE THREAD

**Issue by rpahade3011** [niranjan94/show-java#27]
In my samsung galaxy GT-7100 NOTE 2 decompilation takes hours to decompile an APK, but still app shows a message that dexing your application. What would be the reason for this? My device contains 1.6 Ghz of quad-core processor and 1.74 GB of RAM.

**Comment by AdLindsay** [comment]
A lot of people have had this problem before:
Go to Settings --> Application Manager or Apps --> Show Java --> Clear Data

**Comment by rpahade3011** [comment]
Thanks! It worked...
