### ISSUE TITLE
Check app version while picking app for decompiling

### ISSUE THREAD

**Issue by sachinkamath** [niranjan94/show-java#36]
Right now, the app doesn't check the version of the app before decompiling it. This might create problems when I have source of an older version of  package `com.example.x` and try to decompile a newer version of the same package. Of course, I can click `Decompile` again but it'd be really nice if the app can handle the versions properly. 

Again, thanks for this wonderful app. :dancer: :dancer:

**Comment by BanDanBan1** [comment]
it would actually be best if one could keep (and later compare to each other) the sources of more then one version.
