### ISSUE TITLE
Editor and an IDE

### ISSUE THREAD

**Issue by Shanthosh1** [niranjan94/show-java#37]
It would be very helpful if the app has an editor and a compiler(IDE).It would be very handful and time-saver.

**Comment by niranjan94** [comment]
Hi, that's a good idea. But, this project started as a decompiler. And I would like to keep it like that without  cluttering the app with a loads of features. This project will continue to add more decompilers and optimise the existing process. 

Maybe the IDE and editor could be released as a separate companion app. But cannot make promises regarding that.
