### ISSUE TITLE
Share function

### ISSUE THREAD

**Issue by sjeuquay1224** [niranjan94/show-java#38]
Crash or exit app when click button share

**Comment by niranjan94** [comment]
Seems to be working fine here. What application's source were you trying to
share? Please post a logcat so that I can identify the issue.

**Comment by sjeuquay1224** [comment]
May be my device is not compatible

**Comment by niranjan94** [comment]
@sjeuquay1224 that's not right ... Any device running Android 4.0.4 and above shouldn't be having any problem with the app
