### ISSUE TITLE
Decompiler info

### ISSUE THREAD

**Issue by TheDiamondYT1** [niranjan94/show-java#39]
Add a page to show details about the decompilers and compare them.

This way we can choose the right decompiler for our needs.

E.G: JaDX decompiles variables better than CFR

**Comment by wduqu001** [comment]
I guess, that just a small amount of information would be enough to elucidate the user.

For example:

CFR (http://www.benf.org/other/cfr )

CFR will decompile modern Java features - Java 8 lambdas (pre and post Java beta 103 changes), Java 7 String switches etc, but is written entirely in Java 6.
Author: Lee Benfield 

JADX (https://github.com/skylot/jadx)
Jadx decompiles .class and .jar files, but also it produces Java source code from Android Dex and Apk files. 
Author: Skylot

Hope it helps..
