### ISSUE TITLE
Add an option select which packages to ignore while decompiling

### ISSUE THREAD

**Issue by niranjan94** [niranjan94/show-java#4]
Currently, the packages [here](https://github.com/niranjan94/show-java/blob/master/app/src/main/java/com/njlabs/showjava/processor/JarExtractor.java#L69-L106) are not decompiled to speed up the process and to prevent OutOfMemory errors. But, [shad0vvfax@gmail.com](mailto:shad0vvfax@gmail.com) has suggested that I could add an option for the user to select which libraries to ignore and which not to.

I'm not sure if it's possible to add this without adding the possibility of StackOverflow errors, but i'll give it a try nevertheless. :wink:

**Comment by niranjan94** [comment]
This might take sometime ... :/

**Comment by rancidfrog** [comment]
You should check out [JADX](https://github.com/skylot/jadx).
Someone ported it to [Android](https://github.com/NaikSoftware/jadx), too. 
(Have not tried Android version, though)
As when you open a package using jadx, it is almost instant.
Whereas, showJava is quite slow.

**Comment by niranjan94** [comment]
@rancidfrog The android version is slower than ShowJava ... (that's what happens when we make a PC decompiler to run on android)

**Comment by niranjan94** [comment]
@rancidfrog But you just gave me an idea :wink: ... I'm gonna add jadx too ... So that the users can select which decompiler to use ...

**Comment by niranjan94** [comment]
Commits 7c9b1c60a6653674f1bb51254191fa4b8585bbe4 and 3376892d44cb830c07acdbee6122ffbe6b103822 add option to prevent libraries from being ignored. (can be changed in Settings)
