### ISSUE TITLE
Integrity check error

### ISSUE THREAD

**Issue by Rookman64** [niranjan94/show-java#41]
Whenever I run the app to decompile something on Android, it says integrity check failed

**Comment by fiatCurrency** [comment]
This is happening to me all the time now.
Install the app. It immediately says app has stopped: restart or cancel ?
I do restart and the 'allow external storage' permission pops up. Say OK to this.
Select a file either from installed (still no 'system' files !) or SDcard. Starts decompiling
for about 0.2 seconds then pops up with 'this APK can not be decompiled'. The notification bar still has a notification that it is decompiling. The front screen of the app is spinning on 'optimizing dexs'
