### ISSUE TITLE
Allow decompilation of jar files

### ISSUE THREAD

**Issue by Kaelinator** [niranjan94/show-java#43]
Hello,
     I recently downloaded this app, by the way, it's amazing, to be able to learn from others' code even when I'm not at my computer. The only thing is that I want to be able to decompile the jars that I download from the Internet, but I don't see a practical way to do that. I'm not able to see any files (I can see directories) within my device's /storage/emulated/0/Download . This could be me doing this wrong, or maybe it's a bug. I'm not sure, but feedback is appreciated!
Thanks,
Kael

**Comment by AdLindsay** [comment]
Actually the decompiled files are stored in /storage/emulated/0/ShowJava

ShowJava is designed for decompiling android apps (.apk files), I don't think it can decompile jars.
The reason it's called "ShowJava" is because it could originally decompile jar files, but that feature was removed.

**Comment by Kaelinator** [comment]
Oh, why was that feature removed?

**Comment by AdLindsay** [comment]
I'm not sure myself, but maybe it would be a good idea to add it back because I don't think it would make the size of the app much larger.

**Comment by n82freak** [comment]
Pls make decompile of jar & jad files availeble again... that is a good feature ..
