### ISSUE TITLE
Add UI button to stop decompilation

### ISSUE THREAD

**Issue by Hitechcomputergeek** [niranjan94/show-java#65]
Currently, after choosing an app to decompile, you are taken to a splash screen while the app decompiles, and a notification is created with a "Stop decompilation" button. While you can stop decompilation using the notifications widget, if you hit the device's Back button, you are returned to the app's menu while decompilation continues in the background. There is neither an option to stop decompilation nor any indication that an app is currently being decompiled. If for some reason a user has disabled "Show Notifications" from the App Info page, there is no way to stop decompilation without using Force Stop. 

Somewhere within the app there should be an indication that an app is being decompiled as well as a way to stop it.

Great work btw

**Comment by knightrider-kit** [comment]
Once decompilation started if user clicks cancel decompilation stops but service notification does not go away.
