### ISSUE TITLE
show-java android app has always crashed if clear data/cache is applied in the settings and app is opened next time

### ISSUE THREAD

**Issue by ajit1989** [niranjan94/show-java#73]
Steps to reproduce:

Install show-java
launch the app
Go to the settings/app/show-java
Clear data
Launch the show-java app

Actual:
App is crashed

log:

02-19 14:31:42.137 22163 22276 E AndroidRuntime: Process: com.njlabs.showjava, PID: 22163
02-19 14:31:42.137 22163 22276 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at com.njlabs.showjava.ui.Landing$HistoryLoader.doInBackground$528b683(Landing.java:351)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at com.njlabs.showjava.ui.Landing$HistoryLoader.doInBackground(Landing.java:328)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-19 14:31:42.137 22163 22276 E AndroidRuntime: 	... 4 more
02-19 14:31:42.226 22363 22363 D FirebaseApp: com.google.firebase.auth

**Comment by Charles6666** [comment]
Yes the label of being bug someone must won't everything of mine Charles Lewis Nichols, 3/19/1986 when I was born last social security number is 2718 I think there someone pretending to be me and it's leaving me with nothing.

**Comment by Charles6666** [comment]
Hear I am they was trying too make me trust them and make me deal with there theft with more persure that is illegally breaking the law authority need an Lawsuits for the issue and for touching mine phone now one more time $90. Billion dollars Trump don't have it now cause look who he Harry Harrisment gave it to you know why look watch you have been why would you all allowed this when mine life could be better studios and stage is how I started tell they made me push mine dream mine blessment toward President and I gain Power not people power but mortality power I am who I said I am and there is no issue for these people if I'm just being me so guess who was being them self's as well what thefting police for Trump but cheeks cause they was making me be gay and they was making me taken frames of charges if I would not spread mine that sexual abused i conduction rapt.

**Comment by Charles6666** [comment]
There stealing and trying to hack me for mine phones that I bought. And stealing while I'm sleeping.
