### ISSUE TITLE
Last release lacks APK file

### ISSUE THREAD

**Issue by IzzySoft** [niranjan94/show-java#86]
Hopefully just forgotten: Version 2.1.0 has no `.apk` file attached. Would you be so kind to fill that gap? Of course, if you're just releasing 2.1.1 tomorrow (it's been some time, and maybe the commits – which a.o. contain some fixes – justify a minor release), the gap has been jumped :smile_cat:

**Comment by belochen** [comment]
Ooookkkkkk...
Cool

**Comment by ZeevoX** [comment]
<a href="https://dc606.4shared.com/download/jMCR792oca/Show_Java_210.apk?tsid=20170804-200110-a570372e&sbsr=2718705fb8b6940bf4f33b15c5f519039b3&bip=MTA5Ljc2LjE3NC40&lgfp=2000" target=_blank><img src="https://www.4shared.com/img/jMCR792oca/15daec89fd0/Show_Java_210" border="0"><br>Click me to download the Show Java 2.1.0 APK</a>

You can go ahead and close this issue.

**Comment by IzzySoft** [comment]
@ZeevoX nope, sorry. Thanks for your help, but how shall I know that's really the app made here? I'm not the one to click any link (no offense meant).

**Comment by niranjan94** [comment]
@IzzySoft have attached the apk to the latest release. 

https://github.com/niranjan94/show-java/releases/tag/v2.1.0

**Comment by ZeevoX** [comment]
You can run `keytool -list -printcert -jarfile ShowJava2.0.9.apk`
This will print the certificates for the ShowJava 2.0.9 APK available on Github releases.
Then you can compare the certificate with the one retrieved when you run `keytool -list -printcert -jarfile ShowJava2.1.0.apk`

**Comment by niranjan94** [comment]
> Of course, if you're just releasing 2.1.1 tomorrow

No plans for a release in the next few weeks. But a version 3 is a WIP. :) Finally got some time to start on it. You would be seeing new commits here in the next few days

**Comment by IzzySoft** [comment]
@niranjan94 Thanks!

@ZeevoX as said, no offense – but you cannot expect that from an "average user". Thanks for jumping in to help, though!

**Comment by IzzySoft** [comment]
@niranjan94 it's missing again. Could you please attach it to the last version at least (and then to all future versions)? Thanks in advance!

**Comment by niranjan94** [comment]
HI @IzzySoft ... Sorry about that 😄Forgot to do it. 

Have added the apks to all the releases that were missing it. Will make sure to do it for all future releases too.

**Comment by IzzySoft** [comment]
Thanks a lot! Looks like my auto-updater found them faster than I was able to check :rofl: Already [online in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.njlabs.showjava).

But now I'm a bit shocked: even more trackers have been added, I now count 6. Would it be insolent to ask for a build that comes without the mass (or at least with less)? Normally I'd remove an app from my repo if it has more than 3 trackers. It's probably not necessary to have 2 analytics modules included (currently: Firebase and Crashlytics). And 3 ad modules is a bit overdoing it, would you agree? My users prefer it not to be tracked – or at least not that excessively – and thus would very much appreciate it. So thanks in advance in their name and mine :wink:

**Comment by IzzySoft** [comment]
@niranjan94 ^^ With so many trackers in the app, I will have to remove it from my repo – sorry, but that contradicts my privacy-first approach. If you can provide an APK that comes without (at least 4 of) them, please let me know and I'll add it back. For example, why multiple analytics frameworks? And what for do you need Firebase at all?

**Comment by niranjan94** [comment]
Hi @IzzySoft.. There is one ads module.. Google admob.. And one crash reporting module. Crashlytics. But Google has merged them both into the firebase suite. So I will have to include firebase core to use those two.

```
implementation "com.google.firebase:firebase-core:16.0.6"
implementation "com.google.firebase:firebase-ads:17.1.2"
implementation "com.crashlytics.sdk.android:crashlytics:2.9.8"
```

Google has been shoving firebase down everybody's throats. I don't like it either. But for now I don't see a viable alternative. Crashlytics provides really good reporting. 

Could you give me more info on the other modules that concern you? Perhaps I can give my reasoning or see if I could remove them.

**Comment by IzzySoft** [comment]
Mostly privacy issues, @niranjan94. I'v collected some facts on some of the modules; see e.g. [here](https://android.izzysoft.de/help?topic=modwarnings#crashlytics) for Crashlytics, [AdMob](https://android.izzysoft.de/help?topic=modwarnings#admob), [DoubleClick](https://android.izzysoft.de/help?topic=modwarnings#doubleclick) ([Firebase](https://android.izzysoft.de/help?topic=modwarnings#firebase) belongs into the same category; go to the start of the page for an index). That list is of course very incomplete.

> Perhaps I can give my reasoning or see if I could remove them.

Let me know if that is so and you have a new release coming with less of them. I gladly re-establish your app in my repo then. Thanks for considering!
