### ISSUE TITLE
still old problem 

### ISSUE THREAD

**Issue by pizza23** [niranjan94/show-java#9]
Optimizing dex file ... takes forever :/

**Comment by NotANoob** [comment]
I had the same problem I just did 
Settings>Apps>Show Java>Clear Data
and it worked fine

**Comment by niranjan94** [comment]
@pizza23 .. I'm closing this issue for now. If I'm able to reproduce it, or if I get reports of the same from more users, I'll reopen this ...

**Comment by pizza23** [comment]
Hello,

 

happy news !!!!  :)

 

Settings>Application manager>Show Java>Clear Data (Clear cache)

 

DID THE TRICK !!!  IT WORKS NOW !!!   :)))))))

 

Regard,

Stan

**Comment by pizza23** [comment]
Hello,

 

happy news !!!!  :)

 

Settings>Application manager>Show Java>Clear Data (Clear cache)

 

DID THE TRICK !!!  IT WORKS NOW !!!   :)))))))

 

Regard,

Stan

  

************************************************************

**Comment by OwnageIsMagic** [comment]
it appears after update from market
complete reinstall solves the problem

**Comment by niranjan94** [comment]
Clearing data and cache seems to be perfect fix to this weird issue as of
now.
