### ISSUE TITLE
can't build, missing extra.gradle

### ISSUE THREAD

**Issue by mhashim6** [niranjan94/show-java#97]
I tried to import the app to android studio, however, gradle keeps complaining:
`Gradle sync failed: Could not read script 'C:\Users\DELL\Desktop\show-java-master\app\extra.gradle' as it does not exist.
					Consult IDE log for more details (Help | Show Log) (1s 987ms)`

**Comment by mudassar1** [comment]
**Same Issue with me** :( 
please tell me if you found any solution for this problem!

**Comment by niranjan94** [comment]
Just create an empty `extra.gradle`. No issue.

**Comment by mhashim6** [comment]
well, I did that, it didn't work, as gradle kept complaining about "keys" that were defined, I deleted all the lines related to these keys, also, I cleaned the project, deleted .gradle folder, and gradle built worked fine, however, the dependencies now are the cause of trouble, I'm not sure, but I think some dependencies  are using conflicting versions pf the support libraries, as studio is complaining about that (all com.android.support libraries should use the exact same version) error. and all activities are are marked with red (showing errors).

**Comment by niranjan94** [comment]
For reference

https://github.com/niranjan94/show-java/blob/1a392dc4b8f7b0d684325d005b35e2d93644bba6/.travis.yml#L25-L27
